/* Auto-generated by gen_irx_mods.sh — do not edit. */
#ifndef IRX_MODS_H
#define IRX_MODS_H

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char iomanX_irx[] __attribute__((aligned(16)));
extern const unsigned int  iomanX_irx_size;
extern const unsigned char fileXio_irx[] __attribute__((aligned(16)));
extern const unsigned int  fileXio_irx_size;
extern const unsigned char usbd_irx[] __attribute__((aligned(16)));
extern const unsigned int  usbd_irx_size;
extern const unsigned char bdm_irx[] __attribute__((aligned(16)));
extern const unsigned int  bdm_irx_size;
extern const unsigned char usbmass_bd_irx[] __attribute__((aligned(16)));
extern const unsigned int  usbmass_bd_irx_size;
extern const unsigned char bdmfs_fatfs_irx[] __attribute__((aligned(16)));
extern const unsigned int  bdmfs_fatfs_irx_size;
extern const unsigned char usbhdfsd_irx[] __attribute__((aligned(16)));
extern const unsigned int  usbhdfsd_irx_size;
extern const unsigned char ps2dev9_irx[] __attribute__((aligned(16)));
extern const unsigned int  ps2dev9_irx_size;
extern const unsigned char netman_irx[] __attribute__((aligned(16)));
extern const unsigned int  netman_irx_size;
extern const unsigned char smap_irx[] __attribute__((aligned(16)));
extern const unsigned int  smap_irx_size;

#ifdef __cplusplus
}
#endif

#endif /* IRX_MODS_H */
